server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gamesdb?useSSL=false
    username: root
    password: adminuser001
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate.hbm2ddl.auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
